version: 0.1.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

build:
  verbosity: minimal
  publish_nuget: true
  project: Toppler.sln

before_build:
- nuget restore
after_build:
- ps: .\scripts\pack.ps1

artifacts:
  - path: '*.nupkg' # find all NuGet packages recursively

test:
  categories:
    except:
    - Integration
    
test_script:
- ps: .\scripts\run_tests.ps1
